[package]
name = "hacke-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = {version = "0.12.1", features = ["tokio"]}
open = "5.1.4"
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
serde = "1.0.203"
serde_derive = "1.0.203"
serde_json = "1.0.117"
